### ISSUE TITLE
Saddle plot: setting negative values to vmin vmax 

### ISSUE THREAD

**Issue by betulakgol** [open2c/cooltools#107]
Setting negative values to vmin/vmax gives the error below in the new saddle plot. 

``` 
Traceback (most recent call last):
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/bin/cooltools", line 8, in <module>
    sys.exit(cli())
  File "/home/ba69w/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ba69w/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ba69w/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ba69w/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ba69w/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.7/site-packages/cooltools/cli/compute_saddle.py", line 399, in compute_saddle
    plt.savefig(out_prefix + '.' + ext, bbox_inches='tight')
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2056, in print_figure
    **kwargs)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.7/site-packages/matplotlib/backends/backend_pdf.py", line 2503, in print_pdf
    self.figure.draw(renderer)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.7/site-packages/matplotlib/collections.py", line 2017, in draw
    self.update_scalarmappable()
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.7/site-packages/matplotlib/collections.py", line 763, in update_scalarmappable
    self._facecolors = self.to_rgba(self._A, self._alpha)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.7/site-packages/matplotlib/cm.py", line 289, in to_rgba
    x = self.norm(x)
  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.7/site-packages/matplotlib/colors.py", line 1096, in __call__
    raise ValueError("values must all be positive")
ValueError: values must all be positive
````

Betul

**Comment by nvictus** [comment]
With @Phlya's changes, the `vmin` and `vmax` now always refer to values that are not log-transformed. That means that where you had `--scale log2 --vmin -2 --vmax 2`, you would now use 2^-2 and 2^2 instead, i.e.  `--scale log --vmin 0.25 --vmax 4` to get the same effect.

**Comment by Phlya** [comment]
Sorry this is confusing! Maybe we should add an early-catch error for negative vmin with explanation?

**Comment by sergpolly** [comment]
Or put this gotcha in the description at least.
Docs...

**Comment by betulakgol** [comment]
Thank you for the explanation. It would be great to add vmin, vmax>=0 to the manual. Also it is good to provide informative error to people when they give negative values for vmin/vmax.

**Comment by Phlya** [comment]
https://github.com/mirnylab/cooltools/pull/108 explanation for now

**Comment by Phlya** [comment]
Can add a more informative error tomorrow from work where it's easier to test code.

**Comment by Phlya** [comment]
https://github.com/mirnylab/cooltools/pull/109

**Comment by golobor** [comment]
thank you @Phlya !
