### ISSUE TITLE
AssertionError with cooltools call-dots

### ISSUE THREAD

**Issue by prullens** [open2c/cooltools#209]
Hi,

I'd like to call loops using cooltools' call-dots function. I processed raw Hi-C data using ```HiCPro``` and converted the binned (10Kb) matrix to the ```.cool``` format using ```hicConvertFormat```. Subsequent balancing and computing expected using ```balance``` and ```compute-expected``` all ran without any trouble. I am trying to call loops using the following command (forked from https://github.com/open2c/cooltools/issues/39#issuecomment-434436524):
```
export NUMEXPR_MAX_THREADS=1

cooltools call-dots --output-calls $OUTFN \
                               -v --fdr 0.1 \
                               --max-nans-tolerated 7 \
                               --max-loci-separation 2000000 \
                               --dots-clustering-radius 21000 \
                               --tile-size 2000000 \
                               $COOL_PATH $EXPECTED_PATH
```

I am getting the following Traceback:
```
Traceback (most recent call last):
  File "/home/hub_kind/prullens/.venvs/ESC/bin/cooltools", line 8, in <module>
    sys.exit(cli())
  File "/home/hub_kind/prullens/.venvs/ESC/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/hub_kind/prullens/.venvs/ESC/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/hub_kind/prullens/.venvs/ESC/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hub_kind/prullens/.venvs/ESC/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hub_kind/prullens/.venvs/ESC/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/hub_kind/prullens/.venvs/ESC/lib/python3.8/site-packages/cooltools/cli/call_dots.py", line 315, in call_dots
    gw_hist = dotfinder.scoring_and_histogramming_step(
  File "/home/hub_kind/prullens/.venvs/ESC/lib/python3.8/site-packages/cooltools/dotfinder.py", line 2036, in scoring_and_histogramming_step
    final_hist = reduce(_sum_hists, hchunks)
  File "/home/hub_kind/prullens/.venvs/ESC/lib/python3.8/site-packages/cooltools/dotfinder.py", line 1982, in <lambda>
    job = lambda tile: to_hist(to_score(tile))
  File "/home/hub_kind/prullens/.venvs/ESC/lib/python3.8/site-packages/cooltools/dotfinder.py", line 1107, in histogram_scored_pixels
    assert np.issubdtype(grp_df[obs_raw_name].dtype, np.integer)
AssertionError
```

Inserting ```print(grp_df[obs_raw_name].dtype)``` in ```dotfinder.py```:

gives me:
```
Series([], Name: count, dtype: float64)
```
So indeed not an integer. And also seems to be an empty object?

When I disable the ```assert``` line 1107, the scripts runs and even provides the ```.bedpe``` with over 100K loops. But right after again runs into an error which is now probably related to disabling the ```assert```:
```
KeyError: 37.748364
```

Any help would be much appreciated!

Thanks,

**Comment by prullens** [comment]
Guess I solved it! I converted the ICE normalized ```HiCPro``` matrix to the ```.cool``` format, but should instead have used the raw matrix. When using the latter, all steps including ```call-dots``` run without any trouble!

Best,
