### ISSUE TITLE
call-compartments error

### ISSUE THREAD

**Issue by tarak77** [open2c/cooltools#232]
Hi,
I used hicpro2higlass to get my .cool file of bulk data at 100kb. Now I am trying to call compartments on it. but I get the following error:

```
tas15f@h22-login-25 scnt]$ cooltools call-compartments -o ../scnt_compartments/TE_rep2.bed GSM4349658_TE_rep2.cool
Traceback (most recent call last):
  File "/gpfs/home/tas15f/.local/bin/cooltools", line 10, in <module>
    sys.exit(cli())
  File "/gpfs/research/software/python/anaconda37/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/gpfs/research/software/python/anaconda37/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/gpfs/research/software/python/anaconda37/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/gpfs/research/software/python/anaconda37/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gpfs/research/software/python/anaconda37/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/gpfs/home/tas15f/.local/lib/python3.7/site-packages/cooltools/cli/call_compartments.py", line 157, in call_compartments
    sort_metric=None,
  File "/gpfs/home/tas15f/.local/lib/python3.7/site-packages/cooltools/eigdecomp.py", line 377, in cooler_cis_eig
    if ignore_diags is None
  File "/gpfs/home/tas15f/.local/lib/python3.7/site-packages/cooler/api.py", line 120, in _load_attrs
    return dict(grp[path].attrs)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/gpfs/home/tas15f/.local/lib/python3.7/site-packages/h5py/_hl/group.py", line 288, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'weight' doesn't exist)"
```

Any help will be great!

**Comment by Phlya** [comment]
It seems like your file is not balanced. I am not sure what hicpro2higlass does, but you need to perform balancing (aka iterative correction) at some stage. You can run `cooler balance` on the file to achieve that.

**Comment by tarak77** [comment]
I see. Also the output produced two files....how to interpret those??

**Comment by Phlya** [comment]
One of them is a bed-like file with values of eigenvectors at each bin. The other one shows the eigenvalues, that correspond to the eigenvectors (you probably only need the former).

**Comment by tarak77** [comment]
Makes sense. Thanks!
