### ISSUE TITLE
compute-saddle error

### ISSUE THREAD

**Issue by baishengjun** [open2c/cooltools#267]
Hi,
Thanks for all the great work with cooltools. I got the following error when running compute-saddle, and it confused me many days.  My command line is ` cooltools compute-saddle AR_50k.cool AR.cis.vecs.tsv::E1 AR_expected.tsv::balanced.avg -o AR`. 

Thanks a million,
Bai
```
Traceback (most recent call last):
  File "/mnt/sdf1/boshengjun/miniconda3/bin/cooltools", line 8, in <module>
    sys.exit(cli())
  File "/mnt/sdf1/boshengjun/miniconda3/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/sdf1/boshengjun/miniconda3/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/mnt/sdf1/boshengjun/miniconda3/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/sdf1/boshengjun/miniconda3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/sdf1/boshengjun/miniconda3/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/sdf1/boshengjun/miniconda3/lib/python3.9/site-packages/cooltools/cli/compute_saddle.py", line 402, in compute_saddle
    if len(range_):
TypeError: object of type 'NoneType' has no len()
```

**Comment by baishengjun** [comment]
I have solved this problem by degrading numpy and python version

**Comment by mxw010** [comment]
which version of numpy and python are you running? I didn't have this problem before. Now this is popping up. I'm on cooltools 0.4.0, numpy 1.21.3 and python 3.8.2

**Comment by mxw010** [comment]
I went to 1.19.0 and still got the same error :\

(I think) I fixed it by changing the len(range_) check to if range_ is not None.
