### ISSUE TITLE
cooltools compute-saddle  problem

### ISSUE THREAD

**Issue by J-GL** [open2c/cooltools#279]
First of all many thanks for creating this great set of tools and sharing them.  I have an issue similar to what posted in “compute-expected and saddle problem #242” but I’m still unable to identify the problem

I’m using cooltools v 0.4.0. I am using balanced 50kb matrices in .cool format together with expected_path and matrixeigenvectors files. To generate saddle-plots I am running the following code:
cooltools compute-saddle -o Matrix50kb.cool matrixeigenvectors.cis.vecs.tsv expected_signal 

I get the following error:

INFO:numexpr.utils:NumExpr defaulting to 8 threads.
Traceback (most recent call last):
  File "/home/jonay/anaconda3/envs/Jonay/bin/cooltools", line 11, in <module>
    sys.exit(cli())
  File "/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/lib/python3.7/site-packages/cooltools/cli/compute_saddle.py", line 315, in compute_saddle
    verbose=verbose,
  File "lib/python3.7/site-packages/pandas/io/parsers.py", line 689, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/lib/python3.7/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/lib/python3.7/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/lib/python3.7/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/lib/python3.7/site-packages/pandas/io/parsers.py", line 1924, in __init__
    _validate_usecols_names(usecols, self.orig_names)
  File "/lib/python3.7/site-packages/pandas/io/parsers.py", line 1163, in _validate_usecols_names
    f"Usecols do not match columns, columns expected but not found: {missing}"
ValueError: Usecols do not match columns, columns expected but not found: ['diag', 'balanced.avg', 'region', 'n_valid']

I have changed the order of the columns in “expected_signal” to “diag', 'balanced.avg', 'region', 'n_valid', re-run the code and get the same error asking for a different order of the columns, and this keeps going into a loop if I keep changing the column order.

Any help will be much appreciated!

Thanks a million,

Jonay

**Comment by gfudenberg** [comment]
hi Jonay,
Can you print the first few lines of your expected_signal file? e.g. 
`head -n 4 expected_signal`
This would typically have columns: `region`, `diag`, `n_valid`, `count.sum`, `balanced.sum`, `count.avg`, `balanced.avg`

**Comment by gfudenberg** [comment]
this table looks ok. What chromosome names are used in Matrix50kb.cool & matrixeigenvectors.cis.vecs.tsv ? I wonder if there's a mismatch.

**Comment by gfudenberg** [comment]
closing, as the new release updates the expected format-- please feel free to re-open if new issues emerge
