### ISSUE TITLE
KeyError: 'nnz' during cooltools expected-cis for Genome Architechture Mapping (GAM) matrix data

### ISSUE THREAD

**Issue by sachingadakh** [open2c/cooltools#346]
Hello,
   I want to calculate saddle statistics and generate a saddle plots using compartments (eigs-cis) calculated by the 4DN group on HiC and GAM matrix. 
But first I calculated the expected Hi-C signal for HiC data using cool formatted HiC data which was successful but faced the following error for the GAM matrix (cool formatted data).

Command : cooltools expected-cis 4DNFIZMXOEM8_GAM100KB.cool --clr-weight-name "" -o
4DNFIZMXOEM8_GAM100KB_expect.tsv 

Traceback (most recent call last):
  File "/home/sachin/.pyenv/versions/3.8.3/bin/cooltools", line 8, in <module>
    sys.exit(cli())
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/cooltools/cli/expected_cis.py", line 119, in expected_cis
    result = api.expected.expected_cis(
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/cooltools/api/expected.py", line 1116, in expected_cis
    result = diagsum_symm(
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/cooltools/api/expected.py", line 582, in diagsum_symm
    spans = partition(0, len(clr.pixels()), chunksize)
  File "/home/sachin/.pyenv/versions/3.8.3/lib/python3.8/site-packages/cooler/api.py", line 299, in pixels
    return RangeSelector1D(None, _slice, _fetch, self._info["nnz"])
KeyError: 'nnz'

**Comment by sergpolly** [comment]
Hi @sachingadakh this seems to be an issue with the cooler file itself. `cooltools` relies on a standard cooler files , which should have some required metadata associated with it, yet the cooler file you're using doesn't seem to have at least `nnz` (number of non-zero pixels - or the size of the pixel table) ..

Could you try running `cooler info 4DNFIZMXOEM8_GAM100KB.cool` - just to see what is available there for this file ?

**Comment by nvictus** [comment]
My guess is that when you converted the [bigwig](https://data.4dnucleome.org/files-processed/4DNFISV1IIGW/@@download/4DNFISV1IIGW.bw) file to a TSV with a header, the `start` or `end` column is getting parsed as float with NaNs or something else that can't be coerced to integers (maybe due to empty rows or badly formatted strings).

**Comment by gfudenberg** [comment]
feel free to re-open if the above didn't answer the question!
