### ISSUE TITLE
dump-cworld

### ISSUE THREAD

**Issue by nicholas-moskwa** [open2c/cooltools#349]
Hello,
I am trying to use the 'dump-cworld' function:
cooltools dump-cworld --region 'chr1' ChIA-PET_hg38_GM12878_CTCF_LHG0147_qcseq_pairs_10000.cool ChIA-PET_hg38_GM12878_CTCF_LHG0147_qcseq_pairs_10000.chr1.cool.matrix

Then I get this error about the -region option:
Traceback (most recent call last):
  File "/pod/2/ch-lee-lab/labdata/Packages/miniconda3/envs/cooltools/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'chr1'

Any assistance would be appreciated.
Thank you

**Comment by nvictus** [comment]
Any chance your file uses a different naming convention (e.g. `1` rather than `chr1`)?

You can check via `cooler dump -t chroms ChIA-PET_hg38_GM12878_CTCF_LHG0147_qcseq_pairs_10000.cool`

**Comment by nicholas-moskwa** [comment]
Hi nvictus,
Yep, you were right, we are only numeric. That fixed that issue, but now I see this other error:
Traceback (most recent call last):
  File "/pod/2/ch-lee-lab/labdata/Packages/miniconda3/envs/cooltools/bin/cooltools", line 11, in <module>
    sys.exit(cli())
  File "/pod/2/ch-lee-lab/labdata/Packages/miniconda3/envs/cooltools/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/pod/2/ch-lee-lab/labdata/Packages/miniconda3/envs/cooltools/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/pod/2/ch-lee-lab/labdata/Packages/miniconda3/envs/cooltools/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/pod/2/ch-lee-lab/labdata/Packages/miniconda3/envs/cooltools/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/pod/2/ch-lee-lab/labdata/Packages/miniconda3/envs/cooltools/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/pod/2/ch-lee-lab/labdata/Packages/miniconda3/envs/cooltools/lib/python3.6/site-packages/cooltools/cli/dump_cworld.py", line 67, in dump_cworld
    buffer_size=int(1e8),
  File "/pod/2/ch-lee-lab/labdata/Packages/miniconda3/envs/cooltools/lib/python3.6/site-packages/cooltools/io/cool2cworld.py", line 101, in dump_cworld
    else c.matrix(balance=iced).fetch(region)
  File "/pod/2/ch-lee-lab/labdata/Packages/miniconda3/envs/cooltools/lib/python3.6/site-packages/cooler/core.py", line 574, in fetch
    return self._slice(self.field, i0, i1, j0, j1)
  File "/pod/2/ch-lee-lab/labdata/Packages/miniconda3/envs/cooltools/lib/python3.6/site-packages/cooler/api.py", line 376, in _slice
    self._is_symm_upper,
  File "/pod/2/ch-lee-lab/labdata/Packages/miniconda3/envs/cooltools/lib/python3.6/site-packages/cooler/api.py", line 687, in matrix
    + "calculate balancing weights or set balance=False."
**ValueError: No column 'bins/weight'found. Use ``cooler.balance_cooler`` to calculate balancing weights or set balance=False.**

The .matrix file is empty so there is something I am missing here.
Thank you for your help!

**Comment by nvictus** [comment]
Sounds like your cooler is unbalanced, probably because it is ChIA-PET. If you're happy with raw data, set `--balancing-type raw`, otherwise run `cooler balance` on your input as the error message says.

**Comment by nicholas-moskwa** [comment]
Once again, that fixed it! Thank you nvictus!

**Comment by nicholas-moskwa** [comment]
One last question, is there a way to change the chromosome headings from '1' to 'chr1'?
I appears that all my downstream programs want 'chr' in the headings.

**Comment by nvictus** [comment]
https://cooler.readthedocs.io/en/latest/api.html#cooler.rename_chroms

**Comment by nicholas-moskwa** [comment]
nvictus you the one! Thank you!
