### ISSUE TITLE
Error when using the max-nans-tolerated option

### ISSUE THREAD

**Issue by jclqrs** [open2c/cooltools#352]
I'm trying to run the CLI cooltools dots function and it gives an error when I set the max-nans-tolerated option to 7.  The dots function runs properly when I get rid of the max-nans-tolerated option but keep everything else the same. This happens with cool files that I generated using the distiller pipeline.

Also, I wondering if the first 2 diagonals are considered as nan values? 

Here is the output:

>cooltools dots -o Y7_0h_midg1_rep0to3_10k_loops_nan7_FDR05 -p 16 --fdr 0.05 --view /home/lamj2/mi_tools/mm9_chr1toX.bed --max-nans-tolerated 7 ./Y7_0h_midg1_rep0to3.mcool::/resolutions/10000 Y7_0h_midg1_rep0to3_10k_expected-cis.tsv
INFO:root:Using recommended donut-based kernels with w=5, p=2 for binsize=10000
INFO:root: matrix 19720X19720 to be split into 1089 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 18175X18175 to be split into 961 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 15960X15960 to be split into 729 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 15564X15564 to be split into 676 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 15254X15254 to be split into 676 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 14952X14952 to be split into 625 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 15253X15253 to be split into 676 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 13174X13174 to be split into 484 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 12408X12408 to be split into 441 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 13000X13000 to be split into 484 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 12185X12185 to be split into 441 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 12126X12126 to be split into 441 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 12029X12029 to be split into 441 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 12520X12520 to be split into 441 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 10350X10350 to be split into 324 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 9832X9832 to be split into 289 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 9528X9528 to be split into 256 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 9078X9078 to be split into 256 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 6135X6135 to be split into 121 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 16666X16666 to be split into 784 tiles of 600X600.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root:convolving 878 tiles to build histograms for lambda-bins
INFO:root:creating a Pool of 16 workers to tackle 878 tiles
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
INFO:root:Done building histograms ...
INFO:root:convolving 878 tiles to extract enriched pixels
INFO:root:creating a Pool of 16 workers to tackle 878 tiles
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/multiprocess/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/multiprocess/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py", line 1388, in <lambda>
    job = lambda tile: to_extract(to_score(tile))
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py", line 1025, in extract_scored_pixels
    threshold_of_pixels = threshold.loc[lambda_of_pixels]
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/pandas/core/indexing.py", line 1153, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/pandas/core/indexing.py", line 1093, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: '[nan] not in index'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lamj2/miniconda3/envs/py38/bin/cooltools", line 11, in <module>
    sys.exit(cli())
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/cli/dots.py", line 188, in dots
    nproc=nproc,
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py", line 1622, in dots
    bin2_id_name="bin2_id",
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py", line 1404, in scoring_and_extraction_step
    significant_pixels = pd.concat(filtered_pix_chunks, ignore_index=True)
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 348, in __init__
    objs = list(objs)
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/multiprocess/pool.py", line 325, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/multiprocess/pool.py", line 748, in next
    raise value
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/multiprocess/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/multiprocess/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py", line 1388, in <lambda>
    job = lambda tile: to_extract(to_score(tile))
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/cooltools/api/dotfinder.py", line 1025, in extract_scored_pixels
    threshold_of_pixels = threshold.loc[lambda_of_pixels]
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/pandas/core/indexing.py", line 1153, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/pandas/core/indexing.py", line 1093, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/lamj2/miniconda3/envs/py38/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: '[nan] not in index'

**Comment by gfudenberg** [comment]
hi @jclqrs , sorry for the slow reply-- what version of cooltools are you using?

**Comment by sergpolly** [comment]
recent  fix should address this issue - please feel free to reopen if that happens again
