### ISSUE TITLE
Can't install latest version of CoolTools

### ISSUE THREAD

**Issue by gabedolpten** [open2c/cooltools#355]
Hi,
When I install the latest version of CoolTools I get the following error:

Traceback (most recent call last):
  File "/Genomics/grid/users/gdolsten/.conda/envs/cooltools/bin/cooltools", line 5, in <module>
    from cooltools.cli import cli
  File "/Genomics/grid/users/gdolsten/.conda/envs/cooltools/lib/python3.10/site-packages/cooltools/__init__.py", line 18, in <module>
    from .lib import (
  File "/Genomics/grid/users/gdolsten/.conda/envs/cooltools/lib/python3.10/site-packages/cooltools/lib/numutils.py", line 11, in <module>
    from ._numutils import (
  File "cooltools/lib/_numutils.pyx", line 1, in init cooltools.lib._numutils
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Do you know what may be causing this? I did pip install Cython and pip install numpy prior to installing cooltools.

**Comment by gfudenberg** [comment]
Hi Gabe, there are often package clashes if some are installed via pip and others previously installed via conda. We recommend the environment in open2c_examples as a fresh starting point, since we spent some time resolving package clashes between numba/numpy/etc.
https://github.com/open2c/open2c_examples
Let us know if that resolves the issue!

**Comment by gfudenberg** [comment]
closing, but feel free to reopen!
