### ISSUE TITLE
Errors in calling dots using API  

### ISSUE THREAD

**Issue by zhengdafangyuan** [open2c/cooltools#364]
I used cooltools(version 0.5.1) to call dots for a public Hi-C dataset,  but there was an error in ` cooltools.dots` steps,  could you tell me how the solve this problem, thanks !

```
import pandas as pd
import numpy as np
from itertools import chain

import cooler
import bioframe
import cooltools
from cooltools.lib.numutils import fill_diag

import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import matplotlib.patches as patches
from matplotlib.ticker import EngFormatter

bp_formatter = EngFormatter('b')
def format_ticks(ax, x=True, y=True, rotate=True):
    """format ticks with genomic coordinates as human readable"""
    if y:
        ax.yaxis.set_major_formatter(bp_formatter)
    if x:
        ax.xaxis.set_major_formatter(bp_formatter)
        ax.xaxis.tick_bottom()
    if rotate:
        ax.tick_params(axis='x',rotation=45)

# open cool files( 10kb resolution )
binsize = 10000
hic_cool_file="4DNFIXP4QG5B.mcool"
hic_clr = cooler.Cooler('%s::/resolutions/%d'%(hic_cool_file, binsize) )

# Use bioframe to fetch the genomic features from the UCSC.
hg38_chromsizes = bioframe.fetch_chromsizes('hg38')
hg38_cens = bioframe.fetch_centromeres('hg38')
hg38_arms = bioframe.make_chromarms(hg38_chromsizes, hg38_cens)

# Select only chromosomes that are present in the cooler.
hg38_arms = hg38_arms.set_index("chrom").loc[hic_clr.chromnames].reset_index()

# Call dots
## intra-arm expected
expected = cooltools.expected_cis(
    hic_clr,
    view_df=hg38_arms,
    nproc=16,
)

## call dots
hic_dots_df = cooltools.dots(
    hic_clr,
    expected=expected,
    view_df=hg38_arms,
    max_loci_separation=10_000_000,
    nproc=16,
)
``` 

Error Infomation: 
```
INFO:root:Using recommended donut-based kernels with w=5, p=2 for binsize=10000
INFO:root: matrix 12348X12348 to be split into 625 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 12549X12549 to be split into 676 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 9314X9314 to be split into 361 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 14907X14907 to be split into 900 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 9222X9222 to be split into 361 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 10609X10609 to be split into 484 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 5073X5073 to be split into 121 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 13950X13950 to be split into 784 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 4828X4828 to be split into 100 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 13327X13327 to be split into 729 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 5920X5920 to be split into 144 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 11162X11162 to be split into 529 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 5985X5985 to be split into 144 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 9951X9951 to be split into 400 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 4496X4496 to be split into 81 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 10019X10019 to be split into 441 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 4446X4446 to be split into 81 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 9395X9395 to be split into 361 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 4065X4065 to be split into 81 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 9316X9316 to be split into 361 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 5276X5276 to be split into 121 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 8234X8234 to be split into 289 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 3598X3598 to be split into 64 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 9731X9731 to be split into 400 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 1703X1703 to be split into 16 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 9735X9735 to be split into 400 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 1709X1709 to be split into 16 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 8997X8997 to be split into 324 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 1841X1841 to be split into 16 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 8360X8360 to be split into 289 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 3729X3729 to be split into 64 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 5306X5306 to be split into 121 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 2472X2472 to be split into 25 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 5855X5855 to be split into 144 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 1817X1817 to be split into 16 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 6222X6222 to be split into 169 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 2585X2585 to be split into 36 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 3278X3278 to be split into 49 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 2824X2824 to be split into 36 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 3622X3622 to be split into 64 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 1190X1190 to be split into 9 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 3482X3482 to be split into 49 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 1401X1401 to be split into 9 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 3682X3682 to be split into 64 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 6051X6051 to be split into 169 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 9555X9555 to be split into 400 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 1044X1044 to be split into 9 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root: matrix 4680X4680 to be split into 100 tiles of 500X500.
INFO:root: tiles are padded (width=5) to enable convolution near the edges
INFO:root:convolving 1776 tiles to build histograms for lambda-bins
INFO:root:creating a Pool of 16 workers to tackle 1776 tiles
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
INFO:root:Done building histograms ...
INFO:root:convolving 1776 tiles to extract enriched pixels
INFO:root:creating a Pool of 16 workers to tackle 1776 tiles
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py:797: PerformanceWarning: indexing past lexsort depth may impact performance.
  expected_indexed.loc[region_name, region_name][expected_value_col].to_numpy()
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/multiprocess/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/multiprocess/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py", line 1388, in <lambda>
    job = lambda tile: to_extract(to_score(tile))
  File "/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py", line 1025, in extract_scored_pixels
    threshold_of_pixels = threshold.loc[lambda_of_pixels]
  File "/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/pandas/core/indexing.py", line 1153, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/pandas/core/indexing.py", line 1093, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/zyserver/miniconda3/envs/cooltools/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: '[nan] not in index'
"""

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_214536/2457067522.py in <module>
     13     view_df=hg38_arms,
     14     max_loci_separation=10_000_000,
---> 15     nproc=16,
     16 )

~/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py in dots(clr, expected, expected_value_col, clr_weight_name, view_df, kernels, max_loci_separation, max_nans_tolerated, n_lambda_bins, lambda_bin_fdr, clustering_radius, cluster_filtering, tile_size, nproc)
   1620         nproc=nproc,
   1621         bin1_id_name="bin1_id",
-> 1622         bin2_id_name="bin2_id",
   1623     )
   1624 

~/miniconda3/envs/cooltools/lib/python3.7/site-packages/cooltools/api/dotfinder.py in scoring_and_extraction_step(clr, expected_indexed, expected_value_col, clr_weight_name, tiles, kernels, ledges, thresholds, max_nans_tolerated, loci_separation_bins, nproc, bin1_id_name, bin2_id_name)
   1402         # https://github.com/mirnylab/cooler/blob/9e72ee202b0ac6f9d93fd2444d6f94c524962769/cooler/tools.py#L59
   1403         filtered_pix_chunks = map_(job, tiles, **map_kwargs)
-> 1404         significant_pixels = pd.concat(filtered_pix_chunks, ignore_index=True)
   1405     finally:
   1406         if nproc > 1:

~/miniconda3/envs/cooltools/lib/python3.7/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    309                     stacklevel=stacklevel,
    310                 )
--> 311             return func(*args, **kwargs)
    312 
    313         return wrapper

~/miniconda3/envs/cooltools/lib/python3.7/site-packages/pandas/core/reshape/concat.py in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    302         verify_integrity=verify_integrity,
    303         copy=copy,
--> 304         sort=sort,
    305     )
    306 

~/miniconda3/envs/cooltools/lib/python3.7/site-packages/pandas/core/reshape/concat.py in __init__(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)
    346             objs = [objs[k] for k in keys]
    347         else:
--> 348             objs = list(objs)
    349 
    350         if len(objs) == 0:

~/miniconda3/envs/cooltools/lib/python3.7/site-packages/multiprocess/pool.py in <genexpr>(.0)
    323                     result._set_length
    324                 ))
--> 325             return (item for chunk in result for item in chunk)
    326 
    327     def imap_unordered(self, func, iterable, chunksize=1):

~/miniconda3/envs/cooltools/lib/python3.7/site-packages/multiprocess/pool.py in next(self, timeout)
    746         if success:
    747             return value
--> 748         raise value
    749 
    750     __next__ = next                    # XXX

KeyError: '[nan] not in index'
```

**Comment by nvictus** [comment]
Related to #373

**Comment by gfudenberg** [comment]
hi @zhengdafangyuan -- this might be related to zeros in the expected table. Can you print your expected table for this dataset?
Thank you!

**Comment by sergpolly** [comment]
this should have been fixed in the master branch (not released yet).
Also please consider filtering "bad" arms of the acrocentric chromosomes, as they usually are unmappable and have no data
e.g. like that:
![203405712-a6a90c6b-04e1-4732-a214-100d2e1c04bb](https://user-images.githubusercontent.com/6790270/204078127-15768457-d6c6-4abd-a188-844689d3aa9c.png)

closing for now - please reopen if issue persists
