### ISSUE TITLE
CLI cooltools pileup error reading features

### ISSUE THREAD

**Issue by gfudenberg** [open2c/cooltools#395]
Usecols is provided twice. May just need to modify the following line (& simply remove usecols=default_cols):
https://github.com/open2c/cooltools/blob/a5341aa03f1bbcc1087983f2919602d4f25c333a/cooltools/cli/pileup.py#L175

```Traceback (most recent call last):
  File "/Users/geofffudenberg/anaconda3/envs/open2c/bin/cooltools", line 8, in <module>
    sys.exit(cli())
  File "/Users/geofffudenberg/anaconda3/envs/open2c/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/geofffudenberg/anaconda3/envs/open2c/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/geofffudenberg/anaconda3/envs/open2c/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/geofffudenberg/anaconda3/envs/open2c/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/geofffudenberg/anaconda3/envs/open2c/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/geofffudenberg/anaconda3/envs/open2c/lib/python3.8/site-packages/cooltools/cli/pileup.py", line 175, in pileup
    features_df = pd.read_table(
TypeError: read_table() got multiple values for keyword argument 'usecols' ```

**Comment by gfudenberg** [comment]
fixed in #398
