### ISSUE TITLE
TypeError: read_csv() got an unexpected keyword argument 'all_names'

### ISSUE THREAD

**Issue by Chao-Guo-hub** [open2c/cooltools#408]
`cooltools genome digest susScr11.chrom.sizes susScr11.fa DpnI`

Traceback (most recent call last):
  File "/opt/service/miniconda3/envs/zyp_py3_env/bin/cooltools", line 11, in <module>
    sys.exit(cli())
  File "/opt/service/miniconda3/envs/zyp_py3_env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/service/miniconda3/envs/zyp_py3_env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/service/miniconda3/envs/zyp_py3_env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/service/miniconda3/envs/zyp_py3_env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/service/miniconda3/envs/zyp_py3_env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/service/miniconda3/envs/zyp_py3_env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/service/miniconda3/envs/zyp_py3_env/lib/python3.10/site-packages/cooltools/cli/genome.py", line 48, in digest
    chromsizes = bioframe.read_chromsizes(chromsizes_path, all_names=True)
  File "/opt/service/miniconda3/envs/zyp_py3_env/lib/python3.10/site-packages/bioframe/io/fileops.py", line 128, in read_chromsizes
    chromtable = pd.read_csv(
  File "/opt/service/miniconda3/envs/zyp_py3_env/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/service/miniconda3/envs/zyp_py3_env/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
TypeError: read_csv() got an unexpected keyword argument 'all_names'

**Comment by Chao-Guo-hub** [comment]
I don't know the python language very well, but I read past issues. This looks like a historical version issue?

**Comment by Chao-Guo-hub** [comment]
After I removed `all_names` in the following genome.py code, everything worked fine.
A small suggestion: Prompt the user to download the CHROMSIZES file from UCSC in the document


`@genome.command()
@click.argument("chromsizes_path")
@click.argument("fasta_path")
@click.argument("enzyme_name")
def digest(chromsizes_path, fasta_path, enzyme_name):
    import bioframe

    chromsizes = bioframe.read_chromsizes(chromsizes_path)
    fasta_records = bioframe.load_fasta(fasta_path, engine="pyfaidx", as_raw=True)
    if not chromsizes.index.isin(fasta_records).all():
        raise ValueError(
            "Some chromosomes mentioned in {}"
            " are not found in {}".format(chromsizes_path, fasta_path)
        )
    frags = bioframe.digest(fasta_records, enzyme_name)
    print(frags.to_csv(sep="\t", index=False))

`

**Comment by gfudenberg** [comment]
Thanks for the note @Chao-Guo-hub. Perhaps @nvictus can clarify this?

**Comment by nvictus** [comment]
That's a bug. `all_names=True` should now be `filter_chroms=False`.
