### ISSUE TITLE
eigs-cis CLI error "no track values assigned to region"

### ISSUE THREAD

**Issue by michellea-ng** [open2c/cooltools#425]
Hi! Thanks for this tool and documentation! 

I have a question about the cooltools CLI, specifically eigs-cis. 
`cooltools eigs-cis --phasing-track hg38_gc_100000_CLI.tsv::GC --view hg38_view.bed --out-prefix NlaIII_Rep02_GRCh38_unphased.matrix_eigs-cis --bigwig ../balanced/NlaIII_Rep02_GRCh38_unphased.matrix.mcool::resolutions/100000`

I get the following error:
`/home/mng/.conda/envs/cooler_cooltools/lib/python3.8/site-packages/cooltools/lib/checks.py:550: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for name, group in track.groupby([track.columns[0]]):
Traceback (most recent call last):
  File "/home/mng/.conda/envs/cooler_cooltools/bin/cooltools", line 8, in <module>
    sys.exit(cli())
  File "/home/mng/.conda/envs/cooler_cooltools/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/mng/.conda/envs/cooler_cooltools/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/mng/.conda/envs/cooler_cooltools/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mng/.conda/envs/cooler_cooltools/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mng/.conda/envs/cooler_cooltools/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/mng/.conda/envs/cooler_cooltools/lib/python3.8/site-packages/cooltools/cli/eigs_cis.py", line 166, in eigs_cis
    eigvals, eigvec_table = eigdecomp.eigs_cis(
  File "/home/mng/.conda/envs/cooler_cooltools/lib/python3.8/site-packages/cooltools/api/eigdecomp.py", line 395, in eigs_cis
    phasing_track = align_track_with_cooler(
  File "/home/mng/.conda/envs/cooler_cooltools/lib/python3.8/site-packages/cooltools/lib/common.py", line 502, in align_track_with_cooler
    raise ValueError(
ValueError: no track values assigned to region chr13:0-16000000`

I suspect this is because the region (chr13:0-16000000) is completely masked in the hg38 reference genome, so there are no contacts and also no GC values for this region. I've tried replacing empty values in the GC column with NaNs but this gives the same error.

Is there a way to get around this? Thanks for your time and help!

Best,
Michelle

**Comment by sergpolly** [comment]
I think your suspicion is right - and this error has to do with the fact that `chr13` is acrocentric and `chr13:0-16000000` is the tiny unmappable p-arm ...
cooltools will become more robust to regions like that in the future (show a warning or a more readable error) - but in the meantime you could try to exclude small arms of the acrocentric chromosomes from your `hg38_view.bed` view file

Also - may I ask how did you create your view file ?
You can try to use `bioframe` based method of creating `hg38_arms` e.g. as in this notebook https://github.com/open2c/open2c_examples/blob/master/pileup_CTCF.ipynb (cell N7)

**Comment by gfudenberg** [comment]
closing for now, but feel free to re-open!
