### ISSUE TITLE
virtual4c errors when there is no data

### ISSUE THREAD

**Issue by Phlya** [open2c/cooltools#429]
Need to catch it here https://github.com/open2c/cooltools/blob/c85d647239934b290c844d4db46782aff71db04d/cooltools/api/virtual4c.py#L121
```
Traceback (most recent call last):
  File "/tungstenfs/scratch/ggiorget/ilya/seq_data/microC/C-integration-mapping/.snakemake/conda/461cb23bc9dce2ddd5b4b150b7c95f3d_/bin/cooltools", line 11, in <module>
    sys.exit(cli())
  File "/tungstenfs/scratch/ggiorget/ilya/seq_data/microC/C-integration-mapping/.snakemake/conda/461cb23bc9dce2ddd5b4b150b7c95f3d_/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/tungstenfs/scratch/ggiorget/ilya/seq_data/microC/C-integration-mapping/.snakemake/conda/461cb23bc9dce2ddd5b4b150b7c95f3d_/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/tungstenfs/scratch/ggiorget/ilya/seq_data/microC/C-integration-mapping/.snakemake/conda/461cb23bc9dce2ddd5b4b150b7c95f3d_/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tungstenfs/scratch/ggiorget/ilya/seq_data/microC/C-integration-mapping/.snakemake/conda/461cb23bc9dce2ddd5b4b150b7c95f3d_/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tungstenfs/scratch/ggiorget/ilya/seq_data/microC/C-integration-mapping/.snakemake/conda/461cb23bc9dce2ddd5b4b150b7c95f3d_/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/tungstenfs/scratch/ggiorget/ilya/seq_data/microC/C-integration-mapping/.snakemake/conda/461cb23bc9dce2ddd5b4b150b7c95f3d_/lib/python3.10/site-packages/cooltools/cli/virtual4c.py", line 68, in virtual4c
    v4c = api.virtual4c.virtual4c(
  File "/tungstenfs/scratch/ggiorget/ilya/seq_data/microC/C-integration-mapping/.snakemake/conda/461cb23bc9dce2ddd5b4b150b7c95f3d_/lib/python3.10/site-packages/cooltools/api/virtual4c.py", line 121, in virtual4c
    pd.concat(counts, ignore_index=True),
  File "/tungstenfs/scratch/ggiorget/ilya/seq_data/microC/C-integration-mapping/.snakemake/conda/461cb23bc9dce2ddd5b4b150b7c95f3d_/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/tungstenfs/scratch/ggiorget/ilya/seq_data/microC/C-integration-mapping/.snakemake/conda/461cb23bc9dce2ddd5b4b150b7c95f3d_/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 368, in concat
    op = _Concatenator(
  File "/tungstenfs/scratch/ggiorget/ilya/seq_data/microC/C-integration-mapping/.snakemake/conda/461cb23bc9dce2ddd5b4b150b7c95f3d_/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 448, in __init__
    raise ValueError("All objects passed were None")
ValueError: All objects passed were None
```

**Comment by Phlya** [comment]
Should be fixed now
