### ISSUE TITLE
Unable to install cooltools on Windows

### ISSUE THREAD

**Issue by Devalock** [open2c/cooltools#460]
Hi, I'm trying to install cooltools on Windows OS. Since the cooltools in bioconda doesn't support Windows, I can only try to use `pip install cooltools` and `pip install https://github.com/open2c/cooltools/archive/refs/heads/master.zip`. During the installation, I've met these errors:

```
Building wheels for collected packages: cooltools
  Building wheel for cooltools (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [85 lines of output]
      E:\Projects\miniconda\envs\torch\lib\site-packages\setuptools\__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\cooltools
      copying cooltools\__init__.py -> build\lib.win-amd64-cpython-39\cooltools
      copying cooltools\__main__.py -> build\lib.win-amd64-cpython-39\cooltools
      creating build\lib.win-amd64-cpython-39\cooltools\api
      ………………(lots of similar lines)
      copying cooltools\sandbox\pairs_scaling_functions.py -> build\lib.win-amd64-cpython-39\cooltools\sandbox
      copying cooltools\sandbox\__init__.py -> build\lib.win-amd64-cpython-39\cooltools\sandbox
      running build_ext
      building 'cooltools.lib._numutils' extension
      creating build\temp.win-amd64-cpython-39
      creating build\temp.win-amd64-cpython-39\Release
      creating build\temp.win-amd64-cpython-39\Release\cooltools
      creating build\temp.win-amd64-cpython-39\Release\cooltools\lib
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IE:\Projects\miniconda\envs\torch\lib\site-packages\numpy\core\include -IE:\Projects\miniconda\envs\torch\lib\site-packages\numpy\core\include -IE:\Projects\miniconda\envs\torch\include -IE:\Projects\miniconda\envs\torch\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /Tccooltools/lib/_numutils.c /Fobuild\temp.win-amd64-cpython-39\Release\cooltools/lib/_numutils.obj
      _numutils.c
      E:\Projects\miniconda\envs\torch\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
      cooltools/lib/_numutils.c(6667): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      cooltools/lib/_numutils.c(7613): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      cooltools/lib/_numutils.c(8798): warning C4244: '=': conversion from 'npy_intp' to 'int', possible loss of data
      cooltools/lib/_numutils.c(8852): warning C4013: 'random' undefined; assuming extern returning int
      cooltools/lib/_numutils.c(9223): warning C4244: '=': conversion from 'npy_intp' to 'int', possible loss of data
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:E:\Projects\miniconda\envs\torch\libs /LIBPATH:E:\Projects\miniconda\envs\torch /LIBPATH:E:\Projects\miniconda\envs\torch\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64" /EXPORT:PyInit__numutils build\temp.win-amd64-cpython-39\Release\cooltools/lib/_numutils.obj /OUT:build\lib.win-amd64-cpython-39\cooltools\lib\_numutils.cp39-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-39\Release\cooltools/lib\_numutils.cp39-win_amd64.lib
         Creating library build\temp.win-amd64-cpython-39\Release\cooltools/lib\_numutils.cp39-win_amd64.lib and object build\temp.win-amd64-cpython-39\Release\cooltools/lib\_numutils.cp39-win_amd64.exp
      _numutils.obj : error LNK2001: unresolved external symbol random
      build\lib.win-amd64-cpython-39\cooltools\lib\_numutils.cp39-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cooltools
  Running setup.py clean for cooltools
Failed to build cooltools
ERROR: Could not build wheels for cooltools, which is required to install pyproject.toml-based projects
```

Then I tried to use `pip install --use-pep517 cooltools` as it instructs and it returns `ModuleNotFoundError: No module named 'Cython'`. However, I've already installed it infact.
```
pip install --use-pep517 Cython
Requirement already satisfied: Cython in e:\projects\miniconda\envs\torch\lib\site-packages (3.0.0)
```

So I tried to tackle with the later errors. I searched about `error LNK2001: unresolved external symbol random` and only found maybe I should replace `random()` with `rand()` (https://stackoverflow.com/questions/18726102/what-difference-between-rand-and-random-functions/18726134#18726134). So I downloaded souce code of cooltools and replaced `random()` functions in **cooltools\lib\_numutils.c** with `rand()`, and then `pip install ./`. This time it looks worked and finished installation. However, when I use pyhon to import cooltools, it gives:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Seuche\cooltools-0.5.4\cooltools-0.5.4\cooltools\__init__.py", line 18, in <module>
    from .lib import (
  File "C:\Users\Seuche\cooltools-0.5.4\cooltools-0.5.4\cooltools\lib\numutils.py", line 11, in <module>
    from ._numutils import (
ModuleNotFoundError: No module named 'cooltools.lib._numutils'
```
And I have no idea about this _numutils module. As fat as I know, there is only one `numutils.py` in `lib` directory, and no `_numutils.py`. Now I'm completely lost. I don't know if there are some problems with my installation or it'is not possible to install cooltools on Windows at all. I barely know nothing about C language and hope some could help!

**Comment by alyssaw198** [comment]
I'm running into the same error on my Windows laptop as well. Please let me know if you were able to solve it!

**Comment by gfudenberg** [comment]
Hi all, 

We are not currently supporting windows installations. However, you can try this conda environment specified in the examples github: https://github.com/open2c/open2c_examples/blob/master/environment.yml. You can see we had better luck installing cython via conda rather than pip.

Hope that helps!

**Comment by pghzeng** [comment]
Thanks for your reply. I've tried with conda before, but it also failed.
Now I'm using WSL2 to have a linux environment on Windows. For anyone who is meeting the same problem, this might be a good solution.
