### ISSUE TITLE
KeyError: "Column(s) ['balanced.sum'] do not exist"

### ISSUE THREAD

**Issue by KunFang93** [open2c/cooltools#465]
Hi,

Thanks for providing the wonderful tools! I am trying to use dotfinder to call dot for my customized clr with variable bins size. However, I failed at the first step of calculating the expected with the Error. My cooltools version is 0.5.2.
Here is my code:
```
clr_f = f'/H1_chr17_blocked.cool'
clr = cooler.Cooler(clr_f)

# define genomic view that will be used to call dots and pre-compute expected

# Use bioframe to fetch the genomic features from the UCSC.
hg38_chromsizes = bioframe.fetch_chromsizes('hg38')
hg38_cens = bioframe.fetch_centromeres('hg38')
hg38_arms = bioframe.make_chromarms(hg38_chromsizes, hg38_cens)

# Select only chromosomes that are present in the cooler.
hg38_arms = hg38_arms.set_index("chrom").loc[clr.chromnames].reset_index()

# intra-arm expected
expected = cooltools.expected_cis(
    clr,
    view_df=hg38_arms,
    nproc=4,
    clr_weight_name=None
)
```

The error message:
```
Traceback (most recent call last):
  File "/Users/kfang/miniconda3/envs/nucorg/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-17f14f0ace48>", line 1, in <module>
    expected = cooltools.expected_cis(
  File "/Users/kfang/miniconda3/envs/nucorg/lib/python3.10/site-packages/cooltools/api/expected.py", line 1020, in expected_cis
    result_smooth = expected_smoothing.agg_smooth_cvd(
  File "/Users/kfang/miniconda3/envs/nucorg/lib/python3.10/site-packages/cooltools/sandbox/expected_smoothing.py", line 284, in agg_smooth_cvd
    cvd_smoothed = _agg_smooth_cvd(
  File "/Users/kfang/miniconda3/envs/nucorg/lib/python3.10/site-packages/cooltools/sandbox/expected_smoothing.py", line 217, in _agg_smooth_cvd
    cvd = cvd.set_index(groupby).groupby(groupby).apply(
  File "/Users/kfang/miniconda3/envs/nucorg/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1558, in apply
    result = self._python_apply_general(f, self._selected_obj)
  File "/Users/kfang/miniconda3/envs/nucorg/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1610, in _python_apply_general
    values, mutated = self.grouper.apply(f, data, self.axis)
  File "/Users/kfang/miniconda3/envs/nucorg/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 839, in apply
    res = f(group)
  File "/Users/kfang/miniconda3/envs/nucorg/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1541, in f
    return func(g, *args, **kwargs)
  File "/Users/kfang/miniconda3/envs/nucorg/lib/python3.10/site-packages/cooltools/sandbox/expected_smoothing.py", line 181, in _smooth_cvd_group
    .agg(
  File "/Users/kfang/miniconda3/envs/nucorg/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 894, in aggregate
    result = op.agg()
  File "/Users/kfang/miniconda3/envs/nucorg/lib/python3.10/site-packages/pandas/core/apply.py", line 169, in agg
    return self.agg_dict_like()
  File "/Users/kfang/miniconda3/envs/nucorg/lib/python3.10/site-packages/pandas/core/apply.py", line 478, in agg_dict_like
    arg = self.normalize_dictlike_arg("agg", selected_obj, arg)
  File "/Users/kfang/miniconda3/envs/nucorg/lib/python3.10/site-packages/pandas/core/apply.py", line 601, in normalize_dictlike_arg
    raise KeyError(f"Column(s) {cols_sorted} do not exist")
KeyError: "Column(s) ['balanced.sum'] do not exist"
```

This is the cool [file](https://www.dropbox.com/scl/fi/tp5fdb1yxtkz7v9rpxgv7/H1_chr17_blocked.cool?rlkey=wilr91bgohplkdze6qi5l9heb&dl=0) with only chr17. I wondered if you could shed some lights on how to solve it?

Thanks in advance!

Best,
Kun

**Comment by gfudenberg** [comment]
hi Kun,
what are the keys in your cooler bintable?
e.g. result of clr.bins().keys() ? If your cooler is not balanced it may not have that weight column

**Comment by KunFang93** [comment]
Hi,

Thanks for your reply! Unfortunately, my bins dataframe doesn't have 'weight' columns (['chrom', 'start', 'end', 'arrayid', 'enucidx', 'score', 'size', 'snucidx', 'tag']). I wondered if there is any work around way to calculate the 'expected' without balancing the matrix? I thought ```clr_weight_name=None``` is the parameter that allow me to calculate the 'expected' without balancing the matrix but seems I am wrong... Thank you so much for the help!

Best,
Kun

**Comment by Phlya** [comment]
relevant issue: https://github.com/open2c/cooltools/issues/456
Try setting smooth=False, aggregate_smoothed=False

**Comment by KunFang93** [comment]
It works, thanks!
