### ISSUE TITLE
cooltools insulation  IndexError: positional indexers are out-of-bounds 

### ISSUE THREAD

**Issue by WenjuSun** [open2c/cooltools#522]
Hello,
I am new to Hi-C data analysis and have set up an analysis environment using the following command:
```bash
mamba create --name hicenv pairtools cooler cooltools coolpupp
```
```bash
python --version
# Python 3.10.14
cooltools --version
# cooltools, version 0.7.0
```

When attempting to generate an insulation_table in a Jupyter notebook with the following code:
```python
from cooltools import insulation
resolution=20000
wt_rep12_mcool_r20k = cooler.Cooler(f'{wt_rep12_mcool}::resolutions/{resolution}')
windows = [3*resolution, 5*resolution, 10*resolution, 15*resolution]
insulation_table = insulation(clr=wt_rep12_mcool_r20k, window_bp=windows, nproc=1, verbose=True)
insulation_table.head()
```
I encountered an error with the following message:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
The File ~ / miniforge3 envs/hicenv/lib/python3.10 / site - packages/pandas/core/indexing. The py: 1714, in _iLocIndexer._get_list_axis(self, key, axis)
1713 try:
-> 1714     return self.obj._take_with_is_copy(key, axis=axis)
...
1715 except IndexError as err:
1716     # re-raise with different error message, e.g. test_getitem_ndarray_3d
-> 1717     raise IndexError("positional indexers are out-of-bounds") from err

IndexError: positional indexers are out-of-bounds
```

The same error  (IndexError: positional indexers are out-of-bounds) occurs when running the cooltools insulation command line with:
```bash
cooltools insulation -p 16 -o mESC_WT_HiC.rep12.merged.insulation.r10k.tsv --threshold Li --verbose  mESC_WT_HiC.rep12.merged.1k.zoomify.mcool::resolutions/10000 50000 100000 200000
```
The following information is displayed on the CLI:
```
---------------------------------------------------------------------------
INFO:root:creating a Pool of 16 workers
INFO:root:Processing region chr1
INFO:root:Processing region chr2
INFO:root:Processing region chr3
INFO:root:Processing region chr4
INFO:root:Processing region chr5
INFO:root:Processing region chr6
INFO:root:Processing region chr7
INFO:root:Processing region chr8
INFO:root:Processing region chr9
INFO:root:Processing region chr10
INFO:root:Processing region chr11
INFO:root:Processing region chr12
INFO:root:Processing region chr13
INFO:root:Processing region chr14
INFO:root:Processing region chr15
INFO:root:Processing region chr16
INFO:root:Processing region chr17
INFO:root:Processing region chr18
INFO:root:Processing region chr19
INFO:root:Processing region chrX
INFO:root:Processing region chrY
multiprocess.pool.RemoteTraceback:
"" "
Traceback (most recent call last):
The File "~ / miniforge3 envs/hicenv/lib/python3.10 / site - packages/pandas/core/indexing. Py", line 1714, in _get_list_axis
return self.obj._take_with_is_copy(key, axis=axis)
The File "~ / miniforge3 envs/hicenv/lib/python3.10 / site - packages/pandas/core/generic. Py", line 4153, in _take_with_is_copy
result = self.take(indices=indices, axis=axis)
The File "~ / miniforge3 envs/hicenv/lib/python3.10 / site - packages/pandas/core/generic. Py", line 4133, take in
new_data = self._mgr.take(
File "~ / miniforge3 / envs/hicenv/lib/python3.10 / site - packages/pandas/core/internals/managers. Py", line 891, take in
indexer = maybe_convert_indices(indexer, n, verify=verify)
File "~ / miniforge3 / envs/hicenv/lib/python3.10 / site - packages/pandas/core/indexers/utils. Py", line 282, in maybe_convert_indices
raise IndexError("indices are out-of-bounds")
IndexError: indices are out-of-bounds

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "~ / miniforge3 / envs/hicenv/lib/python3.10 / site - packages/multiprocess/pool. Py", line 125, in the worker
result = (True, func(*args, **kwds))
File "~ / miniforge3 envs/hicenv/lib/python3.10 / site - packages/cooltools/API/insulation. Py", line 331, in _get_region_insulation
ins_track, n_pixels, sum_balanced, sum_counts = insul_diamond(
File "~ / miniforge3 envs/hicenv/lib/python3.10 / site - packages/cooltools/API/insulation. Py", line 111, in insul_diamond
diag_pixels = cooler.annotate(diag_pixels, bins[[clr_weight_name]])
File "~ / miniforge3 / envs/hicenv/lib/python3.10 / site - packages/cooler/API. Py", line 634, in annotate
ann1.iloc[bin1 - bmin]
The File "~ / miniforge3 envs/hicenv/lib/python3.10 / site - packages/pandas/core/indexing. Py", line 1191, in the __getitem__
return self._getitem_axis(maybe_callable, axis=axis)
The File "~ / miniforge3 envs/hicenv/lib/python3.10 / site - packages/pandas/core/indexing. Py", line 1743, in _getitem_axis
return self._get_list_axis(key, axis=axis)
The File "~ / miniforge3 envs/hicenv/lib/python3.10 / site - packages/pandas/core/indexing. Py", line 1717, in _get_list_axis
raise IndexError("positional indexers are out-of-bounds") from err
IndexError: positional indexers are out-of-bounds
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/miniforge3/envs/hicenv/bin/cooltools", line 11, in <module>
    sys.exit(cli())
  File "~/miniforge3/envs/hicenv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "~/miniforge3/envs/hicenv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "~/miniforge3/envs/hicenv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/miniforge3/envs/hicenv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/miniforge3/envs/hicenv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "~/miniforge3/envs/hicenv/lib/python3.10/site-packages/cooltools/cli/insulation.py", line 145, in insulation
    ins_table = api.insulation.insulation(
  File "~/miniforge3/envs/hicenv/lib/python3.10/site-packages/cooltools/api/insulation.py", line 713, in insulation
    ins_table = calculate_insulation_score(
  File "~/miniforge3/envs/hicenv/lib/python3.10/site-packages/cooltools/lib/common.py", line 541, in wrapper
    result = func(*args, **kwargs, map_functor=mymap)
  File "~/miniforge3/envs/hicenv/lib/python3.10/site-packages/cooltools/api/insulation.py", line 275, in calculate_insulation_score
    ins_table = pd.concat(ins_region_tables)
  File "~/miniforge3/envs/hicenv/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 382, in concat
    op = _Concatenator(
  File "~/miniforge3/envs/hicenv/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 445, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
  File "~/miniforge3/envs/hicenv/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 504, in _clean_keys_and_objs
    objs_list = list(objs)
  File "~/miniforge3/envs/hicenv/lib/python3.10/site-packages/multiprocess/pool.py", line 873, in next
    raise value
IndexError: positional indexers are out-of-bounds
---------------------------------------------------------------------------
```

Moreover, I have found, after various attempts, that when the window_bp parameter list gives only one value and that value is equal to the currently used resolution length, although no error is reported, However, the output for log2_insulation_score_{resolution} and boundary_strength_{resolution} are all NaN, and the is_boundary_{resolution} columns are all False, rendering them unusable.

I have confirmed that this issue is not related to our Hi-C data, as the same error message (IndexError: positional indexers are out-of-bounds.) occurs when I follow the tutorial examples provided at [Cooltools Documentation](https://cooltools.readthedocs.io/en/latest/notebooks/insulation_and_boundaries.html) and when running the insulation_and_boundaries.ipynb from [Open2C Examples](https://github.com/open2c/open2c_examples).

I encountered the same error message when running the following steps:
```python
resolution = 10000
clr = cooler.Cooler(f'{data_dir}test.mcool::resolutions/{resolution}')
windows = [3*resolution, 5*resolution, 10*resolution, 25*resolution]
insulation_table = insulation(clr, windows, verbose=True)
` ` `

Has anyone else experienced this problem? What might be causing it, and how can it be resolved?

**Comment by Phlya** [comment]
To solve the error please downgrade cooler to the previous release.

Re window matching the resolution, it's expected since normally the first two diagonals are masked and are filled with NaN values, so the window should be at least 3x resolution (but reasonable values are probably at least 5x resolution I'd say)

**Comment by WenjuSun** [comment]
> To solve the error please downgrade cooler to the previous release.
> 
> Re window matching the resolution, it's expected since normally the first two diagonals are masked and are filled with NaN values, so the window should be at least 3x resolution (but reasonable values are probably at least 5x resolution I'd say)


Wow, Thank you so much for your prompt reply.
By the way, which specific version of cooltools is it better to downgrade to?

**Comment by Phlya** [comment]
Not cooltools - the error comes from cooler. Please try cooler 0.9.3

**Comment by WenjuSun** [comment]
> Not cooltools - the error comes from cooler. Please try cooler 0.9.3

Thank you very much. I've downgraded cooler to 0.9.3 and the command line is currently running fine.
