### ISSUE TITLE
The error in "cooltools.dots"

### ISSUE THREAD

**Issue by jiangfl2854** [open2c/cooltools#543]
When I execute the following command as followed:

binsize = 10_000
clr = cooler.Cooler(f'{data_dir}/new_1k.mcool::/resolutions/{binsize}')
hg38_chromsizes = bioframe.fetch_chromsizes('hg38')
hg38_cens = bioframe.fetch_centromeres('hg38')
hg38_arms = bioframe.make_chromarms(hg38_chromsizes, hg38_cens)
hg38_arms = hg38_arms.set_index("chrom").loc[clr.chromnames].reset_index()
expected = cooltools.expected_cis(clr,view_df=hg38_arms,nproc=4)
dots_df = cooltools.dots(clr,expected=expected,view_df=hg38_arms,max_loci_separation=10_000_000,nproc=4)

It tells me that the following error has occurred:
INFO:root:creating a Pool of 20 workers to tackle 1781 tiles
Traceback (most recent call last):
File "/public/fjzl/zhangzheting/mcool/1-1/Loops.py", line 47, in <module>
dots_df = cooltools.dots(clr,expected=expected,view_df=hg38_arms,max_loci_separation=10_000_000,nproc=20)
File "/public/fjzl/zhangzheting/miniconda3/envs/jfl2/lib/python3.10/site-packages/cooltools/api/dotfinder.py", line 1598, in dots
gw_hist = scoring_and_histogramming_step(
File "/public/fjzl/zhangzheting/miniconda3/envs/jfl2/lib/python3.10/site-packages/cooltools/api/dotfinder.py", line 1336, in scoring_and_histogramming_step
last_lambda_bin = final_hist[k].iloc[:, -1]
File "/public/fjzl/zhangzheting/miniconda3/envs/jfl2/lib/python3.10/site-packages/pandas/core/indexing.py", line 1067, in __getitem__
return self._getitem_tuple(key)
File "/public/fjzl/zhangzheting/miniconda3/envs/jfl2/lib/python3.10/site-packages/pandas/core/indexing.py", line 1563, in _getitem_tuple
tup = self._validate_tuple_indexer(tup)
File "/public/fjzl/zhangzheting/miniconda3/envs/jfl2/lib/python3.10/site-packages/pandas/core/indexing.py", line 873, in _validate_tuple_indexer
self._validate_key(k, i)
File "/public/fjzl/zhangzheting/miniconda3/envs/jfl2/lib/python3.10/site-packages/pandas/core/indexing.py", line 1466, in _validate_key
self._validate_integer(key, axis)
File "/public/fjzl/zhangzheting/miniconda3/envs/jfl2/lib/python3.10/site-packages/pandas/core/indexing.py", line 1557

**Comment by gfudenberg** [comment]
hi @jiangfl2854 -- some more information is needed to help. What version of cooltools & cooler are you using? Was data download successful for the tutorial data?

**Comment by gfudenberg** [comment]
closing for now due to inactivity, feel free to reopen
